services:
  - type: web
    name: media-promotion-bot-free
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "8415474087:AAEDtwjvgogXfvpMzARe875svIEkSSDdNXk"
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-bot-db
          property: connectionString
      - key: Internal Database URL
        value: postgresql://botuser:wvFYbKZY2fLHzxuMIGuIMAcV9ZZTm3dS@dpg-d477doali9vc738hh5fg-a/telegrambotdb_r7m4
