services:
  - type: web
    name: media-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "8415474087:AAEDtwjvgogXfvpMzARe875svIEkSSDdNXk"
      - key: DATABASE_URL
        fromDatabase:
          name: media-db
          property: connectionString

databases:
  - name: media-db
    plan: free
