services:
  - type: web
    name: botrenderdatabase
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-bot-db
          property: connectionString

databases:
  - name: telegram-bot-db
    plan: free
