services:
  - type: web
    name: ammar-simple-db
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: botuser
          property: connectionString
