services:
  - type: web
    name: simple-name-db
    env: python
    plan: free
    pythonVersion: "3.11.0"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: names-db
          property: connectionString

databases:
  - name: names-db
    plan: free
